/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Car_Features;
import Model.Car_ServiceRecord;

import Model.ServiceDetails;
import java.awt.Image;
import java.io.File;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Pavithra Ramkumar
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    String lenValidation;
    Car_Features car_Features;
    Car_ServiceRecord history;
    
    ImageIcon Iicon;
    Image image;
    
    public CreateJPanel(Car_Features car_Features, Car_ServiceRecord history) {
        initComponents();
        this.car_Features = car_Features;
        this.history = history;
        
    }

   // CreateJPanel(Car_Features car_Features, Car_ServiceRecord history) {
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitle = new javax.swing.JLabel();
        LblBrand = new javax.swing.JLabel();
        LblName = new javax.swing.JLabel();
        LblColor = new javax.swing.JLabel();
        LblYear = new javax.swing.JLabel();
        LblEngineNo = new javax.swing.JLabel();
        LblSeatsNumber = new javax.swing.JLabel();
        LblLicensePlate = new javax.swing.JLabel();
        LblOwnerName = new javax.swing.JLabel();
        LblOwnerTelephoneNo = new javax.swing.JLabel();
        LblOwnerEmailAddress = new javax.swing.JLabel();
        LblServiceRecord = new javax.swing.JLabel();
        TxtBrand = new javax.swing.JTextField();
        TxtModel = new javax.swing.JTextField();
        TxtColor = new javax.swing.JTextField();
        TxtYear = new javax.swing.JTextField();
        TxtEngineNo = new javax.swing.JTextField();
        TxtSeatsNumber = new javax.swing.JTextField();
        TxtLicensePlate = new javax.swing.JTextField();
        TxtOwnerName = new javax.swing.JTextField();
        TxtOwnerTelephoneNo = new javax.swing.JTextField();
        TxtOwnerEmailAddress = new javax.swing.JTextField();
        TxtServiceRecord = new javax.swing.JTextField();
        BtSubmit = new javax.swing.JButton();
        LblOwnerSSN = new javax.swing.JLabel();
        TxtOwnerSSN = new javax.swing.JTextField();
        LblOwnerAddress = new javax.swing.JLabel();
        TxtOwnerAddress = new javax.swing.JTextField();
        LblWarrantyYear = new javax.swing.JLabel();
        TxtWarrantyYear = new javax.swing.JTextField();
        BtImage = new javax.swing.JButton();
        LblImage = new javax.swing.JLabel();
        LblFilePath = new javax.swing.JLabel();
        LblDate = new javax.swing.JLabel();
        TxtDate = new javax.swing.JTextField();
        LblWaterWash = new javax.swing.JLabel();
        TxtWaterWash = new javax.swing.JTextField();
        LblPaint = new javax.swing.JLabel();
        TxtPaint = new javax.swing.JTextField();
        LblWheelAlignment = new javax.swing.JLabel();
        TxtWheelAlignment = new javax.swing.JTextField();
        LblCarServiceRecord = new javax.swing.JLabel();
        BtnAddSR = new javax.swing.JButton();

        LblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitle.setText("Car Profile");

        LblBrand.setText("Brand:");

        LblName.setText("Model:");

        LblColor.setText("Color:");

        LblYear.setText("Year:");

        LblEngineNo.setText("Engine No:");

        LblSeatsNumber.setText("Seats No:");

        LblLicensePlate.setText("License Plate:");

        LblOwnerName.setText("OwnerName:");

        LblOwnerTelephoneNo.setText("Owner Telephone Number:");

        LblOwnerEmailAddress.setText("Owner Email Address:");

        LblServiceRecord.setText("Service Record:");

        TxtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBrandActionPerformed(evt);
            }
        });

        TxtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtModelActionPerformed(evt);
            }
        });

        TxtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtColorActionPerformed(evt);
            }
        });

        TxtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtYearActionPerformed(evt);
            }
        });

        TxtEngineNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEngineNoActionPerformed(evt);
            }
        });

        TxtSeatsNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSeatsNumberActionPerformed(evt);
            }
        });

        TxtLicensePlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLicensePlateActionPerformed(evt);
            }
        });

        TxtOwnerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOwnerNameActionPerformed(evt);
            }
        });

        TxtOwnerTelephoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOwnerTelephoneNoActionPerformed(evt);
            }
        });

        TxtOwnerEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOwnerEmailAddressActionPerformed(evt);
            }
        });

        TxtServiceRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtServiceRecordActionPerformed(evt);
            }
        });

        BtSubmit.setText("Submit");
        BtSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSubmitActionPerformed(evt);
            }
        });

        LblOwnerSSN.setText("Owner SSN:");

        TxtOwnerSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOwnerSSNActionPerformed(evt);
            }
        });

        LblOwnerAddress.setText("Owner Address:");

        TxtOwnerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtOwnerAddressActionPerformed(evt);
            }
        });

        LblWarrantyYear.setText("Warranty Year:");

        TxtWarrantyYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtWarrantyYearActionPerformed(evt);
            }
        });

        BtImage.setText("Upload Image");
        BtImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtImageActionPerformed(evt);
            }
        });

        LblDate.setText("Date:");

        TxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDateActionPerformed(evt);
            }
        });

        LblWaterWash.setText("Water Wash:");

        TxtWaterWash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtWaterWashActionPerformed(evt);
            }
        });

        LblPaint.setText("Paint:");

        TxtPaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPaintActionPerformed(evt);
            }
        });

        LblWheelAlignment.setText("Wheel Alignment:");

        TxtWheelAlignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtWheelAlignmentActionPerformed(evt);
            }
        });

        LblCarServiceRecord.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        LblCarServiceRecord.setText("                CAR SERVICE RECORD");

        BtnAddSR.setText("ADD");
        BtnAddSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddSRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LblName)
                        .addComponent(LblBrand)
                        .addComponent(LblColor, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(LblYear)
                    .addComponent(LblEngineNo)
                    .addComponent(LblSeatsNumber)
                    .addComponent(LblLicensePlate)
                    .addComponent(LblOwnerName)
                    .addComponent(LblOwnerTelephoneNo)
                    .addComponent(LblOwnerEmailAddress)
                    .addComponent(LblOwnerSSN)
                    .addComponent(LblOwnerAddress)
                    .addComponent(LblServiceRecord)
                    .addComponent(LblWarrantyYear))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtServiceRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtOwnerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtOwnerEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtOwnerTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtSeatsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(TxtWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblFilePath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtSubmit)
                            .addComponent(BtImage))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblCarServiceRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LblWaterWash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LblPaint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LblWheelAlignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtWaterWash, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtPaint, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtWheelAlignment, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(BtnAddSR)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(LblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LblTitle)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblBrand)
                    .addComponent(TxtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtSubmit))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblName)
                            .addComponent(TxtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblColor)
                            .addComponent(TxtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblYear))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblEngineNo)
                            .addComponent(TxtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblCarServiceRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(BtImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblSeatsNumber)
                            .addComponent(TxtSeatsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LblLicensePlate)
                                        .addComponent(TxtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LblOwnerName)
                                        .addComponent(TxtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LblWaterWash, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtWaterWash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LblOwnerTelephoneNo)
                                    .addComponent(TxtOwnerTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblPaint, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtPaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LblOwnerEmailAddress)
                                    .addComponent(TxtOwnerEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblWheelAlignment, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtWheelAlignment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LblOwnerSSN)
                                    .addComponent(TxtOwnerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LblOwnerAddress)
                                    .addComponent(TxtOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnAddSR)
                                .addGap(18, 18, 18))))
                    .addComponent(LblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblServiceRecord)
                    .addComponent(TxtServiceRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblWarrantyYear)
                    .addComponent(TxtWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBrandActionPerformed

    private void TxtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtModelActionPerformed

    private void TxtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtColorActionPerformed

    private void TxtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtYearActionPerformed

    private void TxtEngineNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEngineNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEngineNoActionPerformed

    private void TxtSeatsNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSeatsNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSeatsNumberActionPerformed

    private void TxtLicensePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLicensePlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLicensePlateActionPerformed

    private void TxtOwnerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOwnerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOwnerNameActionPerformed

    private void TxtOwnerTelephoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOwnerTelephoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOwnerTelephoneNoActionPerformed

    private void TxtOwnerEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOwnerEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOwnerEmailAddressActionPerformed

    private void TxtServiceRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtServiceRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtServiceRecordActionPerformed

    private void BtSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSubmitActionPerformed

        // TODO add your handling code here:
        //if (Objects.isNull(car_Features.getBrand()) && (car_Features.getBrand().length() > 0)) {
        //formErrors.add("brand-name is empty");
        lenValidation = TxtBrand.getText().trim();
        if(!lenValidation.isEmpty() || lenValidation.matches("[A-Za-z]"))
          car_Features.setBrand(TxtBrand.getText());
        else{
            JOptionPane.showMessageDialog(this, "Invalid Brand Name");
        }
        
      
        
        lenValidation = TxtModel.getText().trim();
        if(!lenValidation.isEmpty() || lenValidation.matches("[A-Za-z][0-9]"))
            car_Features.setModel(TxtModel.getText());
         else{
            JOptionPane.showMessageDialog(this, "Invalid Model Name");
        }
        
        lenValidation = TxtColor.getText().trim();
        if(!lenValidation.isEmpty() || lenValidation.matches("[A-Za-z]"))
            car_Features.setColor(TxtColor.getText());
         else{
            JOptionPane.showMessageDialog(this, "invalid Color");
        }
        
         lenValidation = TxtYear.getText().trim();
        
           if(!lenValidation.isEmpty())
           car_Features.setYear(TxtYear.getText());
           else{
                JOptionPane.showMessageDialog(this, "Invalid Year");
                
           }
           if(!lenValidation.matches("[0-9]") && lenValidation.length()<=4)
                car_Features.setYear(TxtYear.getText());
           else{
            JOptionPane.showMessageDialog(this, "Invalid Year");
        }
        
        lenValidation = TxtEngineNo.getText().trim();
        if(!lenValidation.isEmpty() || lenValidation.matches("[A-Za-z][0-9]"))
        car_Features.setEngineNo(TxtEngineNo.getText());
         else{
            JOptionPane.showMessageDialog(this, "Invalid EngineNo");
        }
        
        lenValidation = TxtSeatsNumber.getText().trim();
        if(((!lenValidation.isEmpty()) && (lenValidation.matches("[0-9]")) && (lenValidation.length()<=2 )))
        car_Features.setSeatsNumber(TxtSeatsNumber.getText());
        else{
            JOptionPane.showMessageDialog(this, "Invalid SeatsNumber");
        }
        lenValidation = TxtLicensePlate.getText().trim();
        if(!lenValidation.isEmpty() || lenValidation.matches("[A-Za-z][0-9]"))
            
        car_Features.setLicensePlate(TxtLicensePlate.getText());
        else{
            JOptionPane.showMessageDialog(this, "Invalid License Plate Number");
        }
        lenValidation = TxtOwnerName.getText().trim();
        if(!lenValidation.isEmpty() || lenValidation.matches("[A-Za-z]"))
        car_Features.setOwner_Name(TxtOwnerName.getText());
        else{
            JOptionPane.showMessageDialog(this, "Invalid Owner Name");
        }
        
        
        lenValidation = TxtOwnerTelephoneNo.getText().trim();
        if(!lenValidation.isEmpty())
            car_Features.setOwner_TelephoneNO(TxtOwnerTelephoneNo.getText());
        else{
            JOptionPane.showMessageDialog(this, "Invalid Owner's Telephone Number");
        }
         if(!lenValidation.matches("[0-9]")&& lenValidation.length()<=10)
        car_Features.setOwner_TelephoneNO(TxtOwnerTelephoneNo.getText());
        else{
            JOptionPane.showMessageDialog(this, "Invalid Owner's Telephone Number");
        }
         
         
        lenValidation = TxtOwnerEmailAddress.getText().trim();
        if(!lenValidation.isEmpty() || lenValidation.matches("[A-Za-z][0-9][!@#$%&*()_+=|<>?{}\\\\[\\\\]~-]"))
        car_Features.setOwner_EmailAddress(TxtOwnerEmailAddress.getText());
        else{
            JOptionPane.showMessageDialog(this, "Invalid EmailAddress");
        }
        
        lenValidation = TxtOwnerSSN.getText().trim();
        if(!lenValidation.isEmpty() || lenValidation.matches("[0-9]"))
        car_Features.setOwner_SSN(TxtOwnerSSN.getText());
        else{
            JOptionPane.showMessageDialog(this, "Invalid Social Security Number");
        }
        
        lenValidation = TxtOwnerAddress.getText().trim();
        if(!lenValidation.isEmpty() || lenValidation.matches("[A-Za-z][0-9]"))
        car_Features.setOwner_Address(TxtOwnerAddress.getText());
        else{
            JOptionPane.showMessageDialog(this, "Invalid Owner Address");
        }
        
        lenValidation = TxtServiceRecord.getText().trim();
        if(!lenValidation.isEmpty() || lenValidation.matches("[A-Za-z][0-9]"))
        car_Features.setServiceRecord(TxtServiceRecord.getText());
        else{
            JOptionPane.showMessageDialog(this, "Invalid Service Record");
        }
        
        
        lenValidation = TxtWarrantyYear.getText().trim();
        if(!lenValidation.isEmpty())
            car_Features.setWarrantyYear(TxtWarrantyYear.getText());
            else{
                JOptionPane.showMessageDialog(this, "Invalid Warranty Year");
                }
            if(!lenValidation.matches("[0-9]") && (lenValidation.length()<=4))
                car_Features.setWarrantyYear(TxtWarrantyYear.getText());
             else{
                JOptionPane.showMessageDialog(this, "Invalid Warranty Year");
                }
       
        
        JOptionPane.showMessageDialog(this, "Car Information Saved");
        
        
        
    }//GEN-LAST:event_BtSubmitActionPerformed

    private void TxtOwnerSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOwnerSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOwnerSSNActionPerformed

    private void TxtOwnerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtOwnerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtOwnerAddressActionPerformed

    private void TxtWarrantyYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtWarrantyYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtWarrantyYearActionPerformed

    private void BtImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtImageActionPerformed
        // TODO add your handling code here:
     /*JFileChooser chooser = new JFileChooser();
     
     chooser.showOpenDialog(null);
     File f=chooser.getSelectedFile();
     LblImage.setIcon(new ImageIcon(f.toString()));
     filename=f.getAbsolutePath();
     LblFilePath.setText(filename);
            JOptionPane.showMessageDialog(this, "Image Uploaded");*/
     
     JFileChooser imgPhotoBrowse = new JFileChooser();
        FileNameExtensionFilter objFileExt = new FileNameExtensionFilter("jpeg","gif", "png", "jpg", "IMAGES");
        imgPhotoBrowse.addChoosableFileFilter(objFileExt);
        int objOpenDlg = imgPhotoBrowse.showOpenDialog(null);
        if( objOpenDlg == JFileChooser.APPROVE_OPTION){
          File imgSelectedFile =   imgPhotoBrowse.getSelectedFile();
          String imgSelectedPath = imgSelectedFile.getAbsolutePath();
          JOptionPane.showMessageDialog(null, imgSelectedPath);
          LblFilePath.setText(imgSelectedPath);
          Iicon = new ImageIcon(imgSelectedPath);
          image = Iicon.getImage().getScaledInstance(LblImage.getWidth(),LblImage.getHeight(), Image.SCALE_SMOOTH);
          car_Features.setImage(image);
        }
        
    }//GEN-LAST:event_BtImageActionPerformed

    private void TxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDateActionPerformed

    private void TxtWaterWashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtWaterWashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtWaterWashActionPerformed

    private void TxtPaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPaintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPaintActionPerformed

    private void TxtWheelAlignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtWheelAlignmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtWheelAlignmentActionPerformed

    private void BtnAddSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddSRActionPerformed
        // TODO add your handling code here:
        
        String Date = TxtDate.getText();
        String WaterWash = TxtWaterWash.getText();
        String Paint = TxtPaint.getText();
        String WheelAlignment = TxtWheelAlignment.getText();
        
        ServiceDetails sd = history.addnewRecord();
        
        sd.setDate(Date);
        sd.setWaterWash(WaterWash);
        sd.setPaint(Paint);
        sd.setWheelAlignment(WheelAlignment);
        
        JOptionPane.showMessageDialog(this, "New Record Added");
        
        TxtDate.setText("");
        TxtWaterWash.setText("");
        TxtPaint.setText("");
        TxtWheelAlignment.setText("");
        
        
        
        
        
        
    }//GEN-LAST:event_BtnAddSRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtImage;
    private javax.swing.JButton BtSubmit;
    private javax.swing.JButton BtnAddSR;
    private javax.swing.JLabel LblBrand;
    private javax.swing.JLabel LblCarServiceRecord;
    private javax.swing.JLabel LblColor;
    private javax.swing.JLabel LblDate;
    private javax.swing.JLabel LblEngineNo;
    private javax.swing.JLabel LblFilePath;
    private javax.swing.JLabel LblImage;
    private javax.swing.JLabel LblLicensePlate;
    private javax.swing.JLabel LblName;
    private javax.swing.JLabel LblOwnerAddress;
    private javax.swing.JLabel LblOwnerEmailAddress;
    private javax.swing.JLabel LblOwnerName;
    private javax.swing.JLabel LblOwnerSSN;
    private javax.swing.JLabel LblOwnerTelephoneNo;
    private javax.swing.JLabel LblPaint;
    private javax.swing.JLabel LblSeatsNumber;
    private javax.swing.JLabel LblServiceRecord;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JLabel LblWarrantyYear;
    private javax.swing.JLabel LblWaterWash;
    private javax.swing.JLabel LblWheelAlignment;
    private javax.swing.JLabel LblYear;
    private javax.swing.JTextField TxtBrand;
    private javax.swing.JTextField TxtColor;
    private javax.swing.JTextField TxtDate;
    private javax.swing.JTextField TxtEngineNo;
    private javax.swing.JTextField TxtLicensePlate;
    private javax.swing.JTextField TxtModel;
    private javax.swing.JTextField TxtOwnerAddress;
    private javax.swing.JTextField TxtOwnerEmailAddress;
    private javax.swing.JTextField TxtOwnerName;
    private javax.swing.JTextField TxtOwnerSSN;
    private javax.swing.JTextField TxtOwnerTelephoneNo;
    private javax.swing.JTextField TxtPaint;
    private javax.swing.JTextField TxtSeatsNumber;
    private javax.swing.JTextField TxtServiceRecord;
    private javax.swing.JTextField TxtWarrantyYear;
    private javax.swing.JTextField TxtWaterWash;
    private javax.swing.JTextField TxtWheelAlignment;
    private javax.swing.JTextField TxtYear;
    // End of variables declaration//GEN-END:variables
byte[] photo=null;
String filename=null;


}



